title: My Work
description: >
  <img src="https://github.com/user-attachments/assets/5a0e6044-1ba6-4bcc-83d6-d3ba249104c8"  width="120" style="border-radius:50%; margin-bottom:20px;">
  A driven network engineer with a high aptitude for learning.

  <br>
remote_theme: pages-themes/minimal@v0.2.0
