title: OsaruEdiae
description:  Engineer — hands-on labs exploring enterprise switching, VLAN design, Layer 3 troubleshooting, Codepipeline deployment and more!
author: Edidevi
github_username: Edidevi


# Avatar
avatar: https://github.com/user-attachments/assets/5a0e6044-1ba6-4bcc-83d6-d3ba249104c8

# Navigation
nav:
  - label: Work
    url: "#"
  - label: About
    url: https://edidevi.github.io/About/
  - label: GitHub
    url: https://github.com/Edidevi/My-Work
  - label: Linkedin
    url: https://www.linkedin.com/in/osaru-e-4011a7192/
    

# Stats bar
stats:
  - number: "4"
    label: Labs Published
  - number: L2–L3
    label: Switching Coverage
  - number: OSI
    label: Layers 2 & 3 Focus

# Lab projects
labs:

  - title: Inter VLAN L3 lab
    icon: "🎨"
    url: "https://edidevi.github.io/InterVLAN-L3/"
    concepts:
      - Layer 3 switching
      - SVI configurations
      - Inter-VLAN routing tables

  - title: VLAN L2 trunking lab
    icon: "🎨"
    url: "https://edidevi.github.io/Vlan-trunking-lab"
    concepts:
      - Layer 2 switching
      - Trunking
      - Native Vlans
    
  - title: VLAN L3 Troubleshooting
    icon: "🔍"
    url: "https://edidevi.github.io/Inter-VLAN-L3-troubleshooting/"
    concepts:
      - Layer 3 switching
      - Trunking
      - DHCP
      - Native Vlans

  - title: VLAN L3 Troubleshooting P2
    icon: "🔍"
    url: "https://edidevi.github.io/VLAN-L3-Troubleshooting-P2/"
    concepts:
      - Layer 3 switching
      - Trunking
      - subnetting 
      - DHCP

  - title: VLAN L3 Troubleshooting P3
    icon: "🔍"
    url: "https://edidevi.github.io/VLAN-L3-Troubleshooting-P3/"
    concepts:
      - Layer 3 switching
      - Trunking
      - subnetting 
      - DHCP
      - STP
      
# Footer
footer:
  hosted_on: GitHub Pages
  hosted_url: https://pages.github.com
